### ISSUE TITLE
where is the config.json

### ISSUE THREAD

**Issue by YashDevOP** [koreanpanda345/Pokemon_Bot#3]
hey buddy which type of config.json will  be there and what what things should be there pls add it or thell me or email me at yashranjan6raj@gmail.com.

**Comment by koreanpanda345** [comment]
should just be token, prefix. i sadly don't have the project on my current pc, as i developed it on my older pc. 

If people really want me to continue working on this, then i guess i will revive this. But you can of course help. the only reason why i decided to stop making it, was the stress, and it was eating my time i could be sending with my friends, and my family.

**Comment by koreanpanda345** [comment]
But it will probably be a rewrite, because this structure i used is pretty bad, and want to use a more modern structure, which is using classes to make it. I am thinking of using typescript to make this, as typescript will be useful to  structure data like pokemon data, and such, and type matters feel helps vscode's intellisense, so it will make it less of a hassle to make

**Comment by satyammpandeyy** [comment]
u should add it your self and close this issue pls

**Comment by koreanpanda345** [comment]
as much as i want to add the config file. i don't remember what is on it. and even if i had it, its holds credentials, so it would be pretty stupid of me to release that kind of information to the public. and yes i could make a config example, but this structure is pretty old, and idk what some of it does, or goes to. I am currently rewriting it to have a better structure. but for now, i can't do much for this repo and such.
